### ISSUE TITLE
lnd with nat enabled crashes

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#109]
Most probably related to miniupnp or nat-pmp missing in path

```
Scanning local network for a NAT-PMP enabled device
[ERR] SRVR: Unable to discover a NAT-PMP enabled device on the local network: fork/exec /usr/bin/ip: no such file or directory
[ERR] SRVR: unable to create server: Unable to discover a NAT-PMP enabled device on the local network: fork/exec /usr/bin/ip: no such file or directory
```

**Comment by nolim1t** [comment]
thats a tough one to resolve because the box is within its own docker compose VLAN. Unless we remove docker-compose, which adds more complexity in orchestration.

**Comment by AnotherDroog** [comment]
Good point. Let's defer this to later

**Comment by nolim1t** [comment]
also

```
/usr/bin/ip: no such file or directory
```

**Comment by meeDamian** [comment]
This seems to help: https://github.com/lightningnetwork/lnd/issues/2008

Disabling `ufw` stops `lnd` from insta-crashing, but still doesn't seem to be doing anything.

**Comment by AnotherDroog** [comment]
`lnd_1       | SRVR: Scanning local network for a UPnP enabled device`

Fixed in docker-lnd `nat-fix` branch

PR incoming
