### ISSUE TITLE
Implement varians: variant-{zero,box,blank}

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#12]

**Comment by nolim1t** [comment]
You can use ```uname -m``` to distinquish in the setup scripts.

armv6l is PI zero, armv7l is PI 3

See my fork for examples.  https://github.com/lncm/zero/compare/master...nolim1t:mine-docker

**Comment by nolim1t** [comment]
Let me know when the variants get implemented. 

I'll start adding my docker and box setup scripts into this

**Comment by meeDamian** [comment]
Done with initial/starting `pi-setup.sh` files in https://github.com/lncm/pi-factory/commit/728d3f1bbb3d596810cff9757e57e82547ff458b feel free to report bugs in separate issues.
