### ISSUE TITLE
Blockchain snapshots to speed up first sync

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#126]
https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/FastSync

**Comment by nolim1t** [comment]
can this be used to sync the entire blockchain? 

Lets say if you decide not to go with pruned?

**Comment by AnotherDroog** [comment]
This will be for pruned, about 1000 blocks I would say

**Comment by nolim1t** [comment]
Ideally we make use of [IPFS](https://gateway.ipfs.io/ipfs/QmPJu3J8pY8iRMUnzTJaofX3toKrY3AjoCz1PoBNd2DetQ) to facilitate. I've added an issue for this #159

**Comment by meeDamian** [comment]
I wonder if:

1. We start from the same copy of the blockchain, 
1. Run it on multiple bitcoin nodes,
1. Stop them all after exactly the same block

Will the contents of `blocks/` and `chainstate/` be exactly the same? 🤔 

Would allow for at least some level of auditability.

That way we could, ex:

* Host full, archival chain until block X,
* Host pruned recent chunks

That way anyone willing to audit our "fast-sync" chunk would start from our archival part, setup bitcoind to the same level of pruning, stop bitcoind after a specified block and compared their own state with the chunk hosted by us.

Gotta investigate that.

**Comment by AnotherDroog** [comment]
Added fastsync to `noma fastsync`
