### ISSUE TITLE
Standardize "apps" interfaces 

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#128]
Make sure they're:

* **familiar** - container doesn't change conventional port used by the app within
* **versatile** - all app configuration is available to the container as well
* **composable** - all defaults allow for easy app composition - ex. it's enough to just install bitcoind & lnd to have them work together (might require some extra scripting)

Random thought on _composable_ & RPC credentials, perhaps we could generate RPC credentials based on the ID of the container using them - that way we can easily add **and remove** creds from the config file.

**Comment by nolim1t** [comment]
All  services work by default.

We only change the ports if there is a conflict.

However with web services, everything will run on port 80 through nginx.

**Comment by meeDamian** [comment]
I was talking about the architectural design of individual containers.

I don't want unnecessary entrypoints, rewriting paths, making some things inaccessible/unfhangeable from outside.

We should also come up with a consistent tags for all images built by us, and we should also build all `amd64` images in CI by default.

If we do that, we can be even (hopefully temporarily) uploading `arm` manually and putting a docker manifest in front of them via Travis.

Happy to set it up.

**Comment by nolim1t** [comment]
amd64 doesn’t really help find build issues. 

What works on amd64 doesn’t give much guarantees that it is going to run on the rpi hardware.

That’s the challenge right now.

**Comment by nolim1t** [comment]
The good thing is what works on rpi hardware (arm) will work on desktops

**Comment by meeDamian** [comment]
But having our stack runnable on normal computers is not much work, but opens many more doors into how our software can be used.

**Comment by nolim1t** [comment]
Noma addresses a lot of these issues which can be installed on top of this (or a desktop or VPS)
