### ISSUE TITLE
Add a safety check onto docker-compose for checking if the partitions are mounted

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#134]
Add a safety check onto docker-compose for checking if the partitions are mounted correctly.

In some instances, the partitions don't get mounted correctly so docker-compose ends up creating dummy files in the filesystem.

This particularly becomes an issue after the filesystem has changed.

Another supporting idea: Back up the fstab to /media/important so that the same uuids can be reused

**Comment by AnotherDroog** [comment]
I believe this is taken care of, feel free to reopen otherwise
