### ISSUE TITLE
Update Alpine to the latest and investigate use of postmarketOS for orchestration

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#140]
Also verify if `make_modloop.sh` is no longer necessary, and if that's the case, remove it.

**Comment by AnotherDroog** [comment]
Verified, patching modloop won't be necessary after 3.9.1

**Comment by AnotherDroog** [comment]
There's box 0.4.1 with alpine 3.9.1 image hosted over IPFS 

https://ipfs.io/ipfs/QmX83AUBMAZ39wXJbNvUkSdEhHkTV9WeLtYyrTobLEoZYg

**Comment by AnotherDroog** [comment]
This is done isn’t it? @nolim1t

**Comment by nolim1t** [comment]
No we are still on 3.8.2 

We ran into issues with getting wifi fully working.with the setup which is why that branch reminds in limbo

**Comment by AnotherDroog** [comment]
Okay, here’s an idea, maybe we can reimplement the Pi Box based on postmarketOS easily. 

Their build tools base on apk templates which themselves contain collections of apks. 

After creating an APKBUILD script (basically lncm/noma/install.sh refactored) noma simply gets added to the list of apks to build an image with.

Pre-built pmOS device templates account for hardware differences (Zero, Pi3, Pi4, etc) and can be extended into templates for release types. 

APKs build on our knowledge with shell and alpine. 

pmOS build tools are conveniently installed on Debian+Alpine systems and written in Python to match Noma and docker-compose.

**Comment by AnotherDroog** [comment]
@noaho what’s your take on this?

**Comment by nolim1t** [comment]
Sounds good.. do we have a repo or branch for postmarketos implementation yet?

**Comment by AnotherDroog** [comment]
Well it would still be called pi-factory wouldn’t it? Or Alpine Factory

**Comment by nolim1t** [comment]
If you can work with whats in pi-factory and do a postmarketos implementation of it why then sure.

**Comment by meeDamian** [comment]
Perhaps update the name of this issue?

**Comment by nolim1t** [comment]
Updated. Because 3.9 is not the latest anymore

**Comment by nolim1t** [comment]
Will use latest alpine in #236 and #238
