### ISSUE TITLE
Verify all scripts work with sh

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#141]
Ideally also set up linter for it.

Let's try to avoid bash?

I recommend `sh` + `python3` for more complex things - opinions?

**Comment by AnotherDroog** [comment]
I would recommend the initial stage (`/etc/init.d/lncm`) and related parts to be in `ash`

After the first __reboot__ persistent installation is done.  More complex things can be done with `python3`, which is conveniently installed by `/etc/init.d/lncm-post`

**Comment by meeDamian** [comment]
So… it's possible to have `init.d/` scripts written in anything else than they already are?

What's `#!/sbin/openrc-run` ?

**Comment by AnotherDroog** [comment]
It’s not really possible, they have to be written in openrc compatible ash. 

However they can hand off control to other callables

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
