### ISSUE TITLE
Combine all `/usr/local/sbin/` scripts into `mana`

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#144]
All scripts from `/usr/local/sbin/` should be merged into a single, well documented, with ``--help`, `mana` (name up for a discussion) entrypoint.

Probably ideally also rewrite it all to `python3`.

**Comment by nolim1t** [comment]
its quite possible.  I'll have a create wallet script ready soon

**Comment by meeDamian** [comment]
Replaced by #169
