### ISSUE TITLE
zapconnect support

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#148]
As a container and exposing QR conveniently

**Comment by meeDamian** [comment]
That should just be a part of the dashboard. We'll probably have integrations with multiple LN wallets, and if there's no standard on how passing connstring/macaroon/tls happens, then we'll need a tab/button for each. 

Creating a "dashboard" label, and these issues should ideally be moved to a "dashboard" repo, once it gets created.

**Comment by AnotherDroog** [comment]
go get -d github.com/LN-Zap/lndconnect
cd $GOPATH/src/github.com/LN-Zap/lndconnect
make
`lndconnect` can produce QR codes, or strings

**Comment by AnotherDroog** [comment]
Good point! In that case, it can just be a function in `noma`

**Comment by nolim1t** [comment]
For reference, source code is at https://github.com/LN-Zap/lndconnect

As long as its in the same format that ZAP expects then its fine

**Comment by nolim1t** [comment]
created issue within noma project

**Comment by AnotherDroog** [comment]
> created issue within noma project

Thanks! We can also transfer next time :)
