### ISSUE TITLE
Remove as many files from the repo as possible

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#151]
Remove copies of files from the repo. Instead extract them from downloaded Alpine release in `make_img.sh` script.

**Comment by AnotherDroog** [comment]
Many files will be generated by the programs on first start

It would be nice to avoid downloading the entire alpine release. If we need to fetch files that can’t be generated it might be better to download them from alpine web git

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by meeDamian** [comment]
Since it'll all happen on Travis, it's better to issue less requests, but cryptographically verify them.  As there's no point in optimizing for bandwidth/speed when it happens on an automated external pipeline ;).

**Comment by AnotherDroog** [comment]
Gotcha, I misunderstood initially, thinking you meant remove from image

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by meeDamian** [comment]
Nope, just our repo :).

<small>Sent with Google Pixel 3, Android version 9 patch February 2019, using Sinet 5GHz WiFi and Google Chrome Beta version 73.0.3683.37</small>

**Comment by AnotherDroog** [comment]
`Sent with Google Pixel 3, Android version 9 patch February 2019, using Sinet 5GHz WiFi and Google Chrome Beta version 73.0.3683.37`
🤣

Major cleanup coming in v0.5!

**Comment by nolim1t** [comment]
I think this is still valid. Probably can start removing stuff going forward from the most recent release
