### ISSUE TITLE
Cleanup volumes in docker-compose

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#155]

**Comment by AnotherDroog** [comment]
This is tricky because of docker behavior. 

Gonna need to test it thoroughly 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by meeDamian** [comment]
It seems **very tricky**, if not impossible to be done with Docker volumes.

Should probably entertain other ways to go about it - are there any _"virtual filesystems"_ that we could put in-between docker mounts and actual devices?

**Comment by nolim1t** [comment]
Not valid anymore. Noma I think addresses this
