### ISSUE TITLE
Optimize/standardize docker-compose.yml

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#166]
## `docker-compose.yml`

- [x] Make container addresses consistent 
- [ ] Document (wiki) IP address selection for containers
- [ ] Document conventions for docker container
- [x] Figure out how to properly mount files from containers into `/home/{important,volatile,archive}/`
- [ ] document all exposed ports
- [ ] use `docker-compose.yml` overrides

_Originally posted by @meeDamian in https://github.com/lncm/pi-factory/issues/129#issuecomment-459268765_

**Comment by nolim1t** [comment]
Closing in favor of #236  as any node orchestration should be taken care of by the ```noma``` project
