### ISSUE TITLE
Create/use nginx container

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#167]
What for and why exactly is nginx used right now?

_Originally posted by @meeDamian in https://github.com/lncm/pi-factory/issues/129#issuecomment-459273256_

**Comment by nolim1t** [comment]
nginx is used for aggregating invoicer and soon other web services..

**Comment by meeDamian** [comment]
Great.  I do think we should have sth serving static content, but we should architect a way that can work with multiple apps each wanting sth served.

I gotta look into official nginx images.

**Comment by AnotherDroog** [comment]
I've changed the nginx container we added to a lighter one (~10MB) and will be shipping it with the base image for serving Wifi Manager and Wizard html & proxying api calls
