### ISSUE TITLE
Standardize app namespacing.

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#168]
IDEA: Each installed app gains access to `/home/lncm/APP_NAME/` namespace where it can put all initial config files it needs to run.

Get rid of "template files" in favor of #165

_Originally posted by @meeDamian in https://github.com/lncm/pi-factory/issues/129#issuecomment-459274087_

**Comment by nolim1t** [comment]
Gonna get rid of all this in #236 and #238
