### ISSUE TITLE
wifi isn't working again at latest master

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#181]
Wifi isn't working again at latest master https://github.com/lncm/pi-factory/commit/79bb0c255d9129cb31041916f4843b2934dddba0.  (no LNCM-Box AP or internet connection if I pre-loaded a WPA supplicant file)

To get it working, I restored to commit https://github.com/lncm/pi-factory/commit/6a8f7f071c0fc5dcbc24161a5f9e1077d7593a46

**Comment by nolim1t** [comment]
it appears iotwifi doesn't get loaded

**Comment by nolim1t** [comment]
![5c0eea64-3a1a-440a-b7e2-9a00e77bc07d](https://user-images.githubusercontent.com/83470/53870136-3301b780-402c-11e9-978c-020f8d4570f1.jpeg)

Screenshot

**Comment by AnotherDroog** [comment]
Please test latest release too

**Comment by nolim1t** [comment]
Still not fixed at commit https://github.com/lncm/pi-factory/commit/b22b899332bc2f1518b2ff702aafec8e15528ad6

**Comment by AnotherDroog** [comment]
how does this manifest?

**Comment by nolim1t** [comment]
Removing all the files in lncm-workdir fixes the issue
