### ISSUE TITLE
Configure docker so that it doesn't use up all the space on the SD card

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#198]
# Issue

After a while the SD card gets used up with logfiles.

# Solution

Set a configuration value to stop the docker log files from taking up all the space, or disabling log files if it is possible as we already have logging (is this possible @NoahO ? )

# Temporary fix

Restart docker-compose every week or two.

# Where its an issue

On the food4thought box and my own box,

**Comment by nolim1t** [comment]
Another temporary fix which stops logs completely (so you have to use individual app logs)

```
echo "" > $(docker inspect --format='{{.LogPath}}' compose_btcbox_1)
echo "" > $(docker inspect --format='{{.LogPath}}' compose_btcbox_1)
echo "" > $(docker inspect --format='{{.LogPath}}' compose_invoicerbox_1)
```

**Comment by AnotherDroog** [comment]
Cool that's a good idea as a temporary workaround

**Comment by AnotherDroog** [comment]
What if it's not the logs?

**Comment by nolim1t** [comment]
it seems the main culprit is whats in containers.

**Comment by nolim1t** [comment]
btw that above workaround doesn't stop the box logs, it actually just wipes it temporarily. 

So we don't have to restart docker-compose

We just iterate through all the containers (which I think we should include nginx and iotwifi), and pass

```
echo "" > $(docker inspect --format='{{.LogPath}}' containername)
```

and it will just reset the containers log files

**Comment by AnotherDroog** [comment]
This ties in to #76

**Comment by nolim1t** [comment]
Created issue within noma project to make this a utility for now, as configuring docker and reproducing this issue takes some time.

**Comment by noaho** [comment]
I also doubt this is the logs. To clean up past docker images, builds, etc, use docker system prune command.

**Comment by nolim1t** [comment]
Perhaps  we could put ```docker system prune --force``` on a crontab ?
