### ISSUE TITLE
Update invoicer to 0.3.0

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#209]
Our `docker-compose.yml` is still on 0.1.1!

**Comment by nolim1t** [comment]
Possible but we need to also setup a tool for generating the config. I believe we have the toml library

**Comment by AnotherDroog** [comment]
Ok so this will be a more involved that expected. 

I pulled the toml dependency since that was part of `lncm-post` and it was not used anywhere. 

Best to simply add it to requirements.txt in Noma!

**Comment by nolim1t** [comment]
Yes that's why we haven't used the latest version yet.

We also need to integration test it. 

I think first priority is to get a stable master OR release candidate that can be put in master.

**Comment by AnotherDroog** [comment]
Ok, v0.5 is almost ready

**Comment by nolim1t** [comment]
Starting to work on this as of https://github.com/lncm/pi-factory/pull/218

**Comment by nolim1t** [comment]
Superseceded by #223
