### ISSUE TITLE
OS Only version of pi-factory

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#236]
Use the latest version of Alpine. 

Remove all the bitcoind / lnd node cruft from this and simplify it. 

Have the image script build just an alpine OS image which can easily install the ```noma``` package OR use for some other purpose.

## Requirements

- [x] Support for ```aarch64```. The raspberry pi 3 is more than capable of handling this
- [x] Keep support for ```armhf``` for the zero

## Issues

- [x] IOTWIFI does not work with the latest version of Alpine, however there are workarounds for this.

**Comment by meeDamian** [comment]
I would **love** to see this!

Simple way to bootstrap a minimal, RBP-bootable Alpine into an SD card!

😍

**Comment by nolim1t** [comment]
> I would **love** to see this!
> 
> Simple way to bootstrap a minimal, RBP-bootable Alpine into an SD card!
> 
> 😍

see #238 

Testers welcome!

**Comment by nolim1t** [comment]
On the tip of #238 we have a working pi-zero and 64 bit pi images on alpine with full ext4 persistance!
