### ISSUE TITLE
Make variant of zero without hostapd

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#27]
Make variant of zero without hostapd, but with just base bitcoind

**Comment by meeDamian** [comment]
Perhaps let's replace it with `iotwifi` minus docker stuff?

**Comment by AnotherDroog** [comment]
I’m not going to spend time on this, if someone wants to run alpine without hostapd that’s easy to do as is.

**Comment by meeDamian** [comment]
Yup, me neither for now. Perhaps good to do it later, if there's enough interest and/or keep the issue as a reminder on how it can be done in a quite elegant way.

**Comment by nolim1t** [comment]
Closing
