### ISSUE TITLE
Development / Staging Server

### ISSUE THREAD

**Issue by hitchcott** [lncm/pi-factory#33]
For ease of development, and to have a more reliable demo service, we should set up a staging server - maybe using the ARM hosting provider as discussed.

**Comment by meeDamian** [comment]
If someone wants to buy this server (💳) , I'm happy to set it up and return/split its cost in Bitcoin/LN.

**Comment by meeDamian** [comment]
Gimme an invoice later, so that I can move some money back your direction on that massive LN channel we have :P

**Comment by AnotherDroog** [comment]
We got it, it's dedicated and running armv7 in Paris. Unfortunately it's going to take a bit more work to get Alpine running instead of Debian Stretch

**Comment by meeDamian** [comment]
As discussed in person, let's skip switching host OS to alpine, and just focus on running our alpine containers on it instead.

**Comment by AnotherDroog** [comment]
bitcoind is running now and synced, built from verbatim https://github.com/ruimarinho/docker-bitcoin-core

rpc and other ports don't seem to be exposed to the host, although the container runs with -P

Can someone take a look?

**Comment by AnotherDroog** [comment]
This is fine now, needed to use `--networking host` when starting the container

Currently working on lnd and invoicer-ui for donations

**Comment by nolim1t** [comment]
Need to forward ports.. use the -v switch

**Comment by AnotherDroog** [comment]
-v is for volumes. I used -P to forward all `EXPOSE`’d ports

**Comment by AnotherDroog** [comment]
I'll close this since we got par.lncm.io
