### ISSUE TITLE
Point to alpine?

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#41]
Can we start to change the documentation to point to alpine?

**Comment by nolim1t** [comment]
ACK

**Comment by nolim1t** [comment]
The README in the root of this project should be changed a little.

**Comment by AnotherDroog** [comment]
I've moved everything into archive/ and put alpine in the root directory now that the foundation is  stable enough for further development.

There's still lots of useful stuff in archive/ from the Raspbian & Makefile based box we want to migrate.
