### ISSUE TITLE
Handle usb storage devices

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#47]
- Format and mount storage devices
- Create and add swap with slightly higher priority

**Comment by nolim1t** [comment]
I’d leave formatting out for mass storage.

A particular use case would be syncing bitcoind on a desktop or faster machine and then plugging the drive in.

**Comment by AnotherDroog** [comment]
Started doing this in `ash`, the limitations (no arrays, etc) suggest I better rewrite in Python, which is conveniently installed at this point by docker-compose anyways

**Comment by AnotherDroog** [comment]
As discussed previously there are 3 USB storage devices in our default, supported configuration:
1. **"IMPORTANT"** – _critical files such as node configs, keys_ (could be less than 16GB)
2. **"ARCHIVE"** – _recoverable files such as blocks + chainstate_ (at least 16GB)
3. **"VOLATILE"** – _write intensive files such as swap, logs_ (suggested size 16GB)

**Comment by AnotherDroog** [comment]
Solved symlink issues by directly bind-mounting from docker-compose into usb device paths

**Comment by AnotherDroog** [comment]
Completed using python3 `lncm-usb.py` which is called by `lncm-post` and in turn calls `lncm-usb` with 4 positional arguments, three partition names sorted by size and the size of the largest in bytes.
