### ISSUE TITLE
No LNCM hotspot is showing when using this with the PI ZERO

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#64]
No LNCM hotspot is showing when using this with the PI ZERO.

**Comment by AnotherDroog** [comment]
Does it happen after persistent installation or also before?

**Comment by nolim1t** [comment]
no idea , hotspot doesn't appear to come up on zero

**Comment by nolim1t** [comment]
Working, just need to wait a bit longer with the zero
