### ISSUE TITLE
Add tor to alpine install

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#69]
Add tor for a networking layer so channels can be opened

**Comment by nolim1t** [comment]
Something to take a look at is https://github.com/rdsubhas/docker-tor-privoxy-alpine

**Comment by AnotherDroog** [comment]
Step 1, enable "edge" repo in /etc/apk/repositories
Step 2 `apk update && apk add tor`
There's going to be /etc/tor/torrc.sample once the apk is installed

**Comment by nolim1t** [comment]
I've decided to pre-create the torrc file as part of the installation. It doesn't hurt anyway, the keys are all generated. 

Work has started in PR #82

**Comment by nolim1t** [comment]
Done #82 and #84
