### ISSUE TITLE
Ensure sensitive data is owned by root

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#75]
Configs with secrets such as `bitcoind` `lnd`, etc that are currently in `/home/lncm` need to be owned by a privileged user account (e.g. `root`) and _not_ be world readable.

**Comment by AnotherDroog** [comment]
Best we write a lockdown script that takes care of locking down sshd, adding a firewall, etc

**Comment by nolim1t** [comment]
This is no longer valid as its now a base install
