### ISSUE TITLE
Add docker

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#8]
`curl -fsSL https://get.docker.com -o get-docker.sh`
`sudo sh get-docker.sh`

**Comment by nolim1t** [comment]
that would be cool to have but also having problems trying to build a docker image on the PI zero for some reason so will have to tweak that dockerfile

**Comment by nolim1t** [comment]
I have something working which I'll add once @meeDamian completes #12

**Comment by meeDamian** [comment]
I'd say we install docker `curl -fsSL get.docker.com | sh` on `box` and `blank`, but pull & setup all images only on the `box`.

Also, there's a `pi-setup.sh` file already on master with variants and `pi-init3` merged-in so if you want to go ahead wit it @nolim1t, feel free ^^.

**Comment by nolim1t** [comment]
See pull request #19

**Comment by meeDamian** [comment]
I left some comments there, let's discuss modules and some standardisation of docker images?

**Comment by AnotherDroog** [comment]
Sure, I’ll gather my thoughts tomorrow

**Comment by meeDamian** [comment]
Docker installation added to the `builder` variant. More to follow.

**Comment by AnotherDroog** [comment]
Docker has also been added to variant-alpine, including steps necessary to install docker-compose and deps.

**Comment by meeDamian** [comment]
I think we should focus exclusively on porting everything to `variant-alpine`, make it default, and gradually rewrite other variants to also be alpine-based.

Does it warrant another issue?

**Comment by AnotherDroog** [comment]
Since we’ve got Docker working on Alpine, this issue can be closed and we can open new ones related to porting on a case by case basis
