### ISSUE TITLE
Shutdown/start iotwifi depending on internet connection

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#89]

**Comment by nolim1t** [comment]
Shutting down iotwifi also has a side effect of the avahi service (mDNS discovery) not working anymore

**Comment by AnotherDroog** [comment]
Currently `iotwifi` container also controls the wifi, therefore shutting it down will bring down the wifi.

An alternative solution might be to firewall it when not needed?

**Comment by nolim1t** [comment]
IOTWIFI won't be used (unless we find a good solution to bring it back) in #236 and #238
