### ISSUE TITLE
Auto unlock lnd

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#93]

**Comment by nolim1t** [comment]
Another thing worth looking into is also a tool for **lncli create** upon first install. But I think this can be another issue?

**Comment by AnotherDroog** [comment]
Yes this is better as a separate issue and good point

**Comment by AnotherDroog** [comment]
Place utf-8 encoded text file in /media/important/lnd/sesame.txt with password to have lnd unlocked automatically
