### ISSUE TITLE
Create an electrum server container

### ISSUE THREAD

**Issue by meeDamian** [lncm/pi-factory#94]
Seems like a lot of software out there uses electrum servers, and some allow to specify your own (ex. Eclair). It would be good if we had a container for that (optional?).

Issue obv has a very low priority as of right now, but I thought it's good to leave trace of that idea.

Is that a correct repo for it @AnotherDroog?

**Comment by AnotherDroog** [comment]
This is a good idea and yes I think we can track it here

**Comment by AnotherDroog** [comment]
Since neutrino is a better light client I suggest we close this
